name: robinstanaway
favicon: null
layout_spectrum: 0.50267
typography_spectrum: 0.60614
title: The Art of Robin Stanaway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
